### ISSUE TITLE
It is missing the README

### ISSUE THREAD

**Issue by camilamacedo86** [integr8ly/managed-service-controller#5]

**Comment by sedroche** [comment]
@camilamacedo86 This is a WIP and the README is coming later today ([WIP README](https://github.com/integr8ly/managed-service-controller/compare/managed-service-controller-v1.0.0?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8))

**Comment by camilamacedo86** [comment]
@sedroche tks 👍
